// auth
export const auth = {
    LOG_IN: 'LOG_IN',
    LOG_IN_IN_PROGRESS: 'LOG_IN_IN_PROGRESS',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILED: 'LOG_IN_FAILED',
    LOG_OUT: 'LOG_OUT',
    LOG_OUT_IN_PROGRESS: 'LOG_OUT_IN_PROGRESS',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    LOG_OUT_FAILED: 'LOG_OUT_FAILED',
};
// dashboard
export const dashboard = {
    CHANGE_INPUT: 'CHANGE_INPUT',
};
// books
export const books = {
    GET_BOOKS: 'GET_BOOKS',
    GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILED: 'GET_BOOKS_FAILED',
    ADD_BOOK: 'ADD_BOOK',
    ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
    ADD_BOOK_FAILED: 'ADD_BOOK_FAILED',
};
// Navigation
export const navigation ={
    DISABLE_WRAPPER: 'DISABLE_WRAPPER',
};
